import type { PlayerRecord } from "@/domain/player";

/**
 * Spelers die uit de WKCoach dataset verwijderd zijn (uitgeschakelde landen,
 * roster-wijzigingen), maar nog in een manager's team zitten.
 *
 * Wordt bijgewerkt wanneer de CSV sync spelers verwijdert.
 *
 * Round 3→4 (2026-06-28): 312 spelers van 12 uitgeschakelde teams toegevoegd.
 */
const INACTIVE_WK_PLAYERS: Record<string, PlayerRecord> = {
  "53": {
    id: "53",
    naam: "Ricardo Adé",
    club: "Haïti",
    positie: "DEF",
    prijs: 3.5,
  },
  "54": {
    id: "54",
    naam: "Hannes Delcroix",
    club: "Haïti",
    positie: "DEF",
    prijs: 4.0,
  },
  "55": {
    id: "55",
    naam: "Jean-Kévin Duverne",
    club: "Haïti",
    positie: "DEF",
    prijs: 3.5,
  },
  "56": {
    id: "56",
    naam: "Wilguens Paugain",
    club: "Haïti",
    positie: "DEF",
    prijs: 3.0,
  },
  "57": {
    id: "57",
    naam: "Keeto Thermoncy",
    club: "Haïti",
    positie: "DEF",
    prijs: 3.0,
  },
  "58": {
    id: "58",
    naam: "Jean-Ricner Bellegarde",
    club: "Haïti",
    positie: "MID",
    prijs: 4.0,
  },
  "59": {
    id: "59",
    naam: "Carl Sainté",
    club: "Haïti",
    positie: "MID",
    prijs: 3.0,
  },
  "60": {
    id: "60",
    naam: "Danley Jean Jacques",
    club: "Haïti",
    positie: "MID",
    prijs: 3.5,
  },
  "61": {
    id: "61",
    naam: "Leverton Pierre",
    club: "Haïti",
    positie: "MID",
    prijs: 3.0,
  },
  "62": {
    id: "62",
    naam: "Woodensky Pierre",
    club: "Haïti",
    positie: "MID",
    prijs: 3.0,
  },
  "63": {
    id: "63",
    naam: "Dominique Simon",
    club: "Haïti",
    positie: "MID",
    prijs: 3.0,
  },
  "64": {
    id: "64",
    naam: "Josué Casimir",
    club: "Haïti",
    positie: "FWD",
    prijs: 3.5,
  },
  "65": {
    id: "65",
    naam: "Louicius Deedson",
    club: "Haïti",
    positie: "FWD",
    prijs: 3.5,
  },
  "66": {
    id: "66",
    naam: "Derrick Etienne",
    club: "Haïti",
    positie: "FWD",
    prijs: 3.5,
  },
  "67": {
    id: "67",
    naam: "Yassin Fortuné",
    club: "Haïti",
    positie: "FWD",
    prijs: 3.0,
  },
  "68": {
    id: "68",
    naam: "Wilson Isidor",
    club: "Haïti",
    positie: "FWD",
    prijs: 4.0,
  },
  "69": {
    id: "69",
    naam: "Lenny Joseph",
    club: "Haïti",
    positie: "FWD",
    prijs: 3.5,
  },
  "70": {
    id: "70",
    naam: "Duckens Nazon",
    club: "Haïti",
    positie: "FWD",
    prijs: 4.0,
  },
  "71": {
    id: "71",
    naam: "Frantzdy Pierrot",
    club: "Haïti",
    positie: "FWD",
    prijs: 4.0,
  },
  "72": {
    id: "72",
    naam: "Ruben Providence",
    club: "Haïti",
    positie: "FWD",
    prijs: 3.0,
  },
  "148": {
    id: "148",
    naam: "Ali Abdi",
    club: "Tunesië",
    positie: "DEF",
    prijs: 5.5,
  },
  "149": {
    id: "149",
    naam: "Adem Arous",
    club: "Tunesië",
    positie: "DEF",
    prijs: 4.5,
  },
  "150": {
    id: "150",
    naam: "Mohamed Ben Hamida",
    club: "Tunesië",
    positie: "DEF",
    prijs: 4.0,
  },
  "151": {
    id: "151",
    naam: "Raed Chikhaoui",
    club: "Tunesië",
    positie: "DEF",
    prijs: 4.0,
  },
  "152": {
    id: "152",
    naam: "Moutaz Neffati",
    club: "Tunesië",
    positie: "DEF",
    prijs: 4.5,
  },
  "153": {
    id: "153",
    naam: "Omar Rekik",
    club: "Tunesië",
    positie: "DEF",
    prijs: 4.5,
  },
  "154": {
    id: "154",
    naam: "Yan Valery",
    club: "Tunesië",
    positie: "DEF",
    prijs: 5.0,
  },
  "155": {
    id: "155",
    naam: "Elias Achouri",
    club: "Tunesië",
    positie: "FWD",
    prijs: 4.5,
  },
  "156": {
    id: "156",
    naam: "Khalil Ayari",
    club: "Tunesië",
    positie: "FWD",
    prijs: 3.5,
  },
  "157": {
    id: "157",
    naam: "Firas Chaouat",
    club: "Tunesië",
    positie: "FWD",
    prijs: 5.0,
  },
  "158": {
    id: "158",
    naam: "Rayan Elloumi",
    club: "Tunesië",
    positie: "FWD",
    prijs: 4.0,
  },
  "159": {
    id: "159",
    naam: "Hazem Mastouri",
    club: "Tunesië",
    positie: "FWD",
    prijs: 4.5,
  },
  "160": {
    id: "160",
    naam: "Elias Saad",
    club: "Tunesië",
    positie: "FWD",
    prijs: 4.5,
  },
  "161": {
    id: "161",
    naam: "Sebastian Tounekti",
    club: "Tunesië",
    positie: "FWD",
    prijs: 4.5,
  },
  "188": {
    id: "188",
    naam: "Max Crocombe",
    club: "Nieuw-Zeeland",
    positie: "GK",
    prijs: 4.0,
  },
  "189": {
    id: "189",
    naam: "Alex Paulsen",
    club: "Nieuw-Zeeland",
    positie: "GK",
    prijs: 3.5,
  },
  "190": {
    id: "190",
    naam: "Michael Woud",
    club: "Nieuw-Zeeland",
    positie: "GK",
    prijs: 3.5,
  },
  "191": {
    id: "191",
    naam: "Tyler Bindon",
    club: "Nieuw-Zeeland",
    positie: "DEF",
    prijs: 4.0,
  },
  "192": {
    id: "192",
    naam: "Michael Boxall",
    club: "Nieuw-Zeeland",
    positie: "DEF",
    prijs: 4.0,
  },
  "193": {
    id: "193",
    naam: "Liberato Cacace",
    club: "Nieuw-Zeeland",
    positie: "DEF",
    prijs: 4.0,
  },
  "194": {
    id: "194",
    naam: "Francis De Vries",
    club: "Nieuw-Zeeland",
    positie: "DEF",
    prijs: 3.5,
  },
  "195": {
    id: "195",
    naam: "Callan Elliot",
    club: "Nieuw-Zeeland",
    positie: "DEF",
    prijs: 3.5,
  },
  "196": {
    id: "196",
    naam: "Tim Payne",
    club: "Nieuw-Zeeland",
    positie: "DEF",
    prijs: 4.0,
  },
  "197": {
    id: "197",
    naam: "Nando Pijnaker",
    club: "Nieuw-Zeeland",
    positie: "DEF",
    prijs: 3.5,
  },
  "198": {
    id: "198",
    naam: "Tommy Smith",
    club: "Nieuw-Zeeland",
    positie: "DEF",
    prijs: 3.0,
  },
  "199": {
    id: "199",
    naam: "Finn Surman",
    club: "Nieuw-Zeeland",
    positie: "DEF",
    prijs: 4.0,
  },
  "200": {
    id: "200",
    naam: "Lachlan Bayliss",
    club: "Nieuw-Zeeland",
    positie: "MID",
    prijs: 3.0,
  },
  "201": {
    id: "201",
    naam: "Joe Bell",
    club: "Nieuw-Zeeland",
    positie: "MID",
    prijs: 3.5,
  },
  "202": {
    id: "202",
    naam: "Alex Rufer",
    club: "Nieuw-Zeeland",
    positie: "MID",
    prijs: 3.5,
  },
  "203": {
    id: "203",
    naam: "Marko Stamenic",
    club: "Nieuw-Zeeland",
    positie: "MID",
    prijs: 4.0,
  },
  "204": {
    id: "204",
    naam: "Ryan Thomas",
    club: "Nieuw-Zeeland",
    positie: "MID",
    prijs: 3.5,
  },
  "205": {
    id: "205",
    naam: "Kosta Barbarouses",
    club: "Nieuw-Zeeland",
    positie: "FWD",
    prijs: 4.0,
  },
  "206": {
    id: "206",
    naam: "Matthew Garbett",
    club: "Nieuw-Zeeland",
    positie: "MID",
    prijs: 4.0,
  },
  "207": {
    id: "207",
    naam: "Elijah Just",
    club: "Nieuw-Zeeland",
    positie: "MID",
    prijs: 4.0,
  },
  "208": {
    id: "208",
    naam: "Callum McCowatt",
    club: "Nieuw-Zeeland",
    positie: "FWD",
    prijs: 4.0,
  },
  "209": {
    id: "209",
    naam: "Ben Old",
    club: "Nieuw-Zeeland",
    positie: "DEF",
    prijs: 4.0,
  },
  "210": {
    id: "210",
    naam: "Jesse Randall",
    club: "Nieuw-Zeeland",
    positie: "FWD",
    prijs: 3.5,
  },
  "211": {
    id: "211",
    naam: "Sarpreet Singh",
    club: "Nieuw-Zeeland",
    positie: "MID",
    prijs: 4.0,
  },
  "212": {
    id: "212",
    naam: "Ben Waine",
    club: "Nieuw-Zeeland",
    positie: "FWD",
    prijs: 4.0,
  },
  "213": {
    id: "213",
    naam: "Chris Wood",
    club: "Nieuw-Zeeland",
    positie: "FWD",
    prijs: 5.0,
  },
  "396": {
    id: "396",
    naam: "Arda Güler",
    club: "Turkije",
    positie: "MID",
    prijs: 9.5,
  },
  "397": {
    id: "397",
    naam: "Darwin Núñez",
    club: "Uruguay",
    positie: "FWD",
    prijs: 9.5,
  },
  "459": {
    id: "459",
    naam: "Ferdi Kadioglu",
    club: "Turkije",
    positie: "DEF",
    prijs: 9.0,
  },
  "460": {
    id: "460",
    naam: "Hakan Çalhanoglu",
    club: "Turkije",
    positie: "MID",
    prijs: 9.0,
  },
  "461": {
    id: "461",
    naam: "Kerem Aktürkoglu",
    club: "Turkije",
    positie: "FWD",
    prijs: 9.0,
  },
  "462": {
    id: "462",
    naam: "Baris Alper Yilmaz",
    club: "Turkije",
    positie: "FWD",
    prijs: 9.0,
  },
  "463": {
    id: "463",
    naam: "Kenan Yildiz",
    club: "Turkije",
    positie: "FWD",
    prijs: 9.0,
  },
  "464": {
    id: "464",
    naam: "Ronald Araújo",
    club: "Uruguay",
    positie: "DEF",
    prijs: 9.0,
  },
  "465": {
    id: "465",
    naam: "Federico Valverde",
    club: "Uruguay",
    positie: "MID",
    prijs: 9.0,
  },
  "494": {
    id: "494",
    naam: "Patrik Schick",
    club: "Tsjechië",
    positie: "FWD",
    prijs: 8.5,
  },
  "542": {
    id: "542",
    naam: "Ugurcan Çakir",
    club: "Turkije",
    positie: "GK",
    prijs: 8.5,
  },
  "543": {
    id: "543",
    naam: "Abdülkerim Bardakci",
    club: "Turkije",
    positie: "DEF",
    prijs: 8.5,
  },
  "544": {
    id: "544",
    naam: "Zeki Çelik",
    club: "Turkije",
    positie: "DEF",
    prijs: 8.5,
  },
  "545": {
    id: "545",
    naam: "Orkun Kökçü",
    club: "Turkije",
    positie: "MID",
    prijs: 8.5,
  },
  "546": {
    id: "546",
    naam: "Fernando Muslera",
    club: "Uruguay",
    positie: "GK",
    prijs: 8.5,
  },
  "547": {
    id: "547",
    naam: "José María Giménez",
    club: "Uruguay",
    positie: "DEF",
    prijs: 8.5,
  },
  "548": {
    id: "548",
    naam: "Mathías Olivera",
    club: "Uruguay",
    positie: "DEF",
    prijs: 8.5,
  },
  "549": {
    id: "549",
    naam: "Giorgian de Arrascaeta",
    club: "Uruguay",
    positie: "MID",
    prijs: 8.5,
  },
  "550": {
    id: "550",
    naam: "Maximiliano Araújo",
    club: "Uruguay",
    positie: "DEF",
    prijs: 8.5,
  },
  "574": {
    id: "574",
    naam: "Pavel Sulc",
    club: "Tsjechië",
    positie: "MID",
    prijs: 8.0,
  },
  "636": {
    id: "636",
    naam: "Altay Bayindir",
    club: "Turkije",
    positie: "GK",
    prijs: 8.0,
  },
  "637": {
    id: "637",
    naam: "Mert Günok",
    club: "Turkije",
    positie: "GK",
    prijs: 8.0,
  },
  "638": {
    id: "638",
    naam: "Kaan Ayhan",
    club: "Turkije",
    positie: "DEF",
    prijs: 8.0,
  },
  "639": {
    id: "639",
    naam: "Merih Demiral",
    club: "Turkije",
    positie: "DEF",
    prijs: 8.0,
  },
  "640": {
    id: "640",
    naam: "Mert Müldür",
    club: "Turkije",
    positie: "DEF",
    prijs: 8.0,
  },
  "641": {
    id: "641",
    naam: "Ozan Kabak",
    club: "Turkije",
    positie: "DEF",
    prijs: 8.0,
  },
  "642": {
    id: "642",
    naam: "Yunus Akgün",
    club: "Turkije",
    positie: "FWD",
    prijs: 8.0,
  },
  "643": {
    id: "643",
    naam: "Santiago Mele",
    club: "Uruguay",
    positie: "GK",
    prijs: 8.0,
  },
  "644": {
    id: "644",
    naam: "Sergio Rochet",
    club: "Uruguay",
    positie: "GK",
    prijs: 8.0,
  },
  "645": {
    id: "645",
    naam: "Joaquín Piquerez",
    club: "Uruguay",
    positie: "DEF",
    prijs: 8.0,
  },
  "646": {
    id: "646",
    naam: "Matías Viña",
    club: "Uruguay",
    positie: "DEF",
    prijs: 8.0,
  },
  "647": {
    id: "647",
    naam: "Santiago Bueno",
    club: "Uruguay",
    positie: "DEF",
    prijs: 8.0,
  },
  "648": {
    id: "648",
    naam: "Sebastián Cáceres",
    club: "Uruguay",
    positie: "DEF",
    prijs: 8.0,
  },
  "649": {
    id: "649",
    naam: "Facundo Pellistri",
    club: "Uruguay",
    positie: "FWD",
    prijs: 8.0,
  },
  "651": {
    id: "651",
    naam: "Nicolás De La Cruz",
    club: "Uruguay",
    positie: "MID",
    prijs: 8.0,
  },
  "652": {
    id: "652",
    naam: "Rodrigo Bentancur",
    club: "Uruguay",
    positie: "MID",
    prijs: 8.0,
  },
  "672": {
    id: "672",
    naam: "Ladislav Krejcí",
    club: "Tsjechië",
    positie: "DEF",
    prijs: 7.5,
  },
  "673": {
    id: "673",
    naam: "Vladimír Coufal",
    club: "Tsjechië",
    positie: "DEF",
    prijs: 7.5,
  },
  "674": {
    id: "674",
    naam: "Tomáš Soucek",
    club: "Tsjechië",
    positie: "MID",
    prijs: 7.5,
  },
  "675": {
    id: "675",
    naam: "Adam Hložek",
    club: "Tsjechië",
    positie: "FWD",
    prijs: 7.5,
  },
  "723": {
    id: "723",
    naam: "Eren Elmali",
    club: "Turkije",
    positie: "DEF",
    prijs: 7.5,
  },
  "725": {
    id: "725",
    naam: "Ismail Yüksek",
    club: "Turkije",
    positie: "MID",
    prijs: 7.5,
  },
  "726": {
    id: "726",
    naam: "Salih Özcan",
    club: "Turkije",
    positie: "MID",
    prijs: 7.5,
  },
  "727": {
    id: "727",
    naam: "Deniz Gül",
    club: "Turkije",
    positie: "FWD",
    prijs: 7.5,
  },
  "728": {
    id: "728",
    naam: "Samet Akaydin",
    club: "Turkije",
    positie: "DEF",
    prijs: 7.5,
  },
  "729": {
    id: "729",
    naam: "Irfan Kahveci",
    club: "Turkije",
    positie: "FWD",
    prijs: 7.5,
  },
  "730": {
    id: "730",
    naam: "Oguz Aydin",
    club: "Turkije",
    positie: "FWD",
    prijs: 7.5,
  },
  "732": {
    id: "732",
    naam: "Manuel Ugarte",
    club: "Uruguay",
    positie: "MID",
    prijs: 7.5,
  },
  "733": {
    id: "733",
    naam: "Emiliano Martínez",
    club: "Uruguay",
    positie: "MID",
    prijs: 7.5,
  },
  "734": {
    id: "734",
    naam: "Guillermo Varela",
    club: "Uruguay",
    positie: "DEF",
    prijs: 7.5,
  },
  "737": {
    id: "737",
    naam: "Agustín Canobbio",
    club: "Uruguay",
    positie: "FWD",
    prijs: 7.5,
  },
  "738": {
    id: "738",
    naam: "Brian Rodríguez",
    club: "Uruguay",
    positie: "FWD",
    prijs: 7.5,
  },
  "739": {
    id: "739",
    naam: "Federico Viñas",
    club: "Uruguay",
    positie: "FWD",
    prijs: 7.5,
  },
  "756": {
    id: "756",
    naam: "Matej Kovár",
    club: "Tsjechië",
    positie: "GK",
    prijs: 7.0,
  },
  "757": {
    id: "757",
    naam: "David Jurásek",
    club: "Tsjechië",
    positie: "DEF",
    prijs: 7.0,
  },
  "759": {
    id: "759",
    naam: "Robin Hranác",
    club: "Tsjechië",
    positie: "DEF",
    prijs: 7.0,
  },
  "760": {
    id: "760",
    naam: "Štepán Chaloupek",
    club: "Tsjechië",
    positie: "DEF",
    prijs: 7.0,
  },
  "761": {
    id: "761",
    naam: "Tomáš Holeš",
    club: "Tsjechië",
    positie: "DEF",
    prijs: 7.0,
  },
  "763": {
    id: "763",
    naam: "Lukáš Provod",
    club: "Tsjechië",
    positie: "MID",
    prijs: 7.0,
  },
  "764": {
    id: "764",
    naam: "Vladimír Darida",
    club: "Tsjechië",
    positie: "MID",
    prijs: 7.0,
  },
  "765": {
    id: "765",
    naam: "Mojmír Chytil",
    club: "Tsjechië",
    positie: "FWD",
    prijs: 7.0,
  },
  "766": {
    id: "766",
    naam: "Tomáš Chorý",
    club: "Tsjechië",
    positie: "FWD",
    prijs: 7.0,
  },
  "796": {
    id: "796",
    naam: "Lukáš Hornícek",
    club: "Tsjechië",
    positie: "GK",
    prijs: 6.5,
  },
  "798": {
    id: "798",
    naam: "Jaroslav Zelený",
    club: "Tsjechië",
    positie: "DEF",
    prijs: 6.5,
  },
  "799": {
    id: "799",
    naam: "Lukas Cerv",
    club: "Tsjechië",
    positie: "MID",
    prijs: 6.5,
  },
  "800": {
    id: "800",
    naam: "Michal Sadílek",
    club: "Tsjechië",
    positie: "MID",
    prijs: 6.5,
  },
  "841": {
    id: "841",
    naam: "Denis Visinsky",
    club: "Tsjechië",
    positie: "MID",
    prijs: 6.0,
  },
  "913": {
    id: "913",
    naam: "Ellyes Skhiri",
    club: "Tunesië",
    positie: "MID",
    prijs: 5.5,
  },
  "914": {
    id: "914",
    naam: "Hannibal Mejbri",
    club: "Tunesië",
    positie: "MID",
    prijs: 5.5,
  },
  "961": {
    id: "961",
    naam: "Salem Al-Dawsari",
    club: "Saudi-Arabië",
    positie: "MID",
    prijs: 5.0,
  },
  "963": {
    id: "963",
    naam: "Aymen Dahmen",
    club: "Tunesië",
    positie: "GK",
    prijs: 5.0,
  },
  "964": {
    id: "964",
    naam: "Dylan Bronn",
    club: "Tunesië",
    positie: "DEF",
    prijs: 5.0,
  },
  "965": {
    id: "965",
    naam: "Montassar Talbi",
    club: "Tunesië",
    positie: "DEF",
    prijs: 5.0,
  },
  "968": {
    id: "968",
    naam: "Ismaël Gharbi",
    club: "Tunesië",
    positie: "MID",
    prijs: 5.0,
  },
  "991": {
    id: "991",
    naam: "Armando Obispo",
    club: "Curaçao",
    positie: "DEF",
    prijs: 4.5,
  },
  "992": {
    id: "992",
    naam: "Tahith Chong",
    club: "Curaçao",
    positie: "MID",
    prijs: 4.5,
  },
  "1011": {
    id: "1011",
    naam: "Ibrahim Bayesh",
    club: "Irak",
    positie: "MID",
    prijs: 4.5,
  },
  "1012": {
    id: "1012",
    naam: "Ali Al-Hamadi",
    club: "Irak",
    positie: "FWD",
    prijs: 4.5,
  },
  "1013": {
    id: "1013",
    naam: "Aymen Hussein",
    club: "Irak",
    positie: "FWD",
    prijs: 4.5,
  },
  "1014": {
    id: "1014",
    naam: "Mohanad Ali",
    club: "Irak",
    positie: "FWD",
    prijs: 4.5,
  },
  "1017": {
    id: "1017",
    naam: "Amir Murillo",
    club: "Panama",
    positie: "DEF",
    prijs: 4.5,
  },
  "1018": {
    id: "1018",
    naam: "Akram Afif",
    club: "Qatar",
    positie: "FWD",
    prijs: 4.5,
  },
  "1019": {
    id: "1019",
    naam: "Almoez Ali",
    club: "Qatar",
    positie: "FWD",
    prijs: 4.5,
  },
  "1020": {
    id: "1020",
    naam: "Saud Abdulhamid",
    club: "Saudi-Arabië",
    positie: "DEF",
    prijs: 4.5,
  },
  "1021": {
    id: "1021",
    naam: "Musab Al-Juwayr",
    club: "Saudi-Arabië",
    positie: "MID",
    prijs: 4.5,
  },
  "1023": {
    id: "1023",
    naam: "Firas Al-Buraikan",
    club: "Saudi-Arabië",
    positie: "FWD",
    prijs: 4.5,
  },
  "1046": {
    id: "1046",
    naam: "Eloy Room",
    club: "Curaçao",
    positie: "GK",
    prijs: 4.0,
  },
  "1047": {
    id: "1047",
    naam: "Joshua Brenet",
    club: "Curaçao",
    positie: "DEF",
    prijs: 4.0,
  },
  "1048": {
    id: "1048",
    naam: "Juriën Gaari",
    club: "Curaçao",
    positie: "DEF",
    prijs: 4.0,
  },
  "1049": {
    id: "1049",
    naam: "Riechedly Bazoer",
    club: "Curaçao",
    positie: "DEF",
    prijs: 4.0,
  },
  "1050": {
    id: "1050",
    naam: "Roshon van Eijma",
    club: "Curaçao",
    positie: "DEF",
    prijs: 4.0,
  },
  "1051": {
    id: "1051",
    naam: "Sherel Floranus",
    club: "Curaçao",
    positie: "DEF",
    prijs: 4.0,
  },
  "1052": {
    id: "1052",
    naam: "Shurandy Sambo",
    club: "Curaçao",
    positie: "DEF",
    prijs: 4.0,
  },
  "1053": {
    id: "1053",
    naam: "Juninho Bacuna",
    club: "Curaçao",
    positie: "MID",
    prijs: 4.0,
  },
  "1054": {
    id: "1054",
    naam: "Leandro Bacuna",
    club: "Curaçao",
    positie: "MID",
    prijs: 4.0,
  },
  "1055": {
    id: "1055",
    naam: "Livano Comenencia",
    club: "Curaçao",
    positie: "MID",
    prijs: 4.0,
  },
  "1056": {
    id: "1056",
    naam: "Brandley Kuwas",
    club: "Curaçao",
    positie: "FWD",
    prijs: 4.0,
  },
  "1057": {
    id: "1057",
    naam: "Gervane Kastaneer",
    club: "Curaçao",
    positie: "FWD",
    prijs: 4.0,
  },
  "1058": {
    id: "1058",
    naam: "Jürgen Locadia",
    club: "Curaçao",
    positie: "FWD",
    prijs: 4.0,
  },
  "1059": {
    id: "1059",
    naam: "Kenji Gorré",
    club: "Curaçao",
    positie: "FWD",
    prijs: 4.0,
  },
  "1060": {
    id: "1060",
    naam: "Sontje Hansen",
    club: "Curaçao",
    positie: "FWD",
    prijs: 4.0,
  },
  "1074": {
    id: "1074",
    naam: "Ahmed Basil",
    club: "Irak",
    positie: "GK",
    prijs: 4.0,
  },
  "1075": {
    id: "1075",
    naam: "Jalal Hassan",
    club: "Irak",
    positie: "GK",
    prijs: 4.0,
  },
  "1076": {
    id: "1076",
    naam: "Akam Hashim",
    club: "Irak",
    positie: "DEF",
    prijs: 4.0,
  },
  "1077": {
    id: "1077",
    naam: "Frans Putros",
    club: "Irak",
    positie: "DEF",
    prijs: 4.0,
  },
  "1078": {
    id: "1078",
    naam: "Hussein Ali",
    club: "Irak",
    positie: "DEF",
    prijs: 4.0,
  },
  "1079": {
    id: "1079",
    naam: "Manaf Younis",
    club: "Irak",
    positie: "DEF",
    prijs: 4.0,
  },
  "1080": {
    id: "1080",
    naam: "Merchas Doski",
    club: "Irak",
    positie: "DEF",
    prijs: 4.0,
  },
  "1081": {
    id: "1081",
    naam: "Zaid Tahseen",
    club: "Irak",
    positie: "DEF",
    prijs: 4.0,
  },
  "1082": {
    id: "1082",
    naam: "Aimar Sher",
    club: "Irak",
    positie: "MID",
    prijs: 4.0,
  },
  "1083": {
    id: "1083",
    naam: "Ali Jasim",
    club: "Irak",
    positie: "MID",
    prijs: 4.0,
  },
  "1084": {
    id: "1084",
    naam: "Amir Al-Ammari",
    club: "Irak",
    positie: "MID",
    prijs: 4.0,
  },
  "1085": {
    id: "1085",
    naam: "Zidane Iqbal",
    club: "Irak",
    positie: "MID",
    prijs: 4.0,
  },
  "1086": {
    id: "1086",
    naam: "Ehsan Haddad",
    club: "Jordanië",
    positie: "DEF",
    prijs: 4.0,
  },
  "1087": {
    id: "1087",
    naam: "Ali Olwan",
    club: "Jordanië",
    positie: "FWD",
    prijs: 4.0,
  },
  "1088": {
    id: "1088",
    naam: "Musa Tamari",
    club: "Jordanië",
    positie: "FWD",
    prijs: 4.0,
  },
  "1091": {
    id: "1091",
    naam: "Luis Mejía",
    club: "Panama",
    positie: "GK",
    prijs: 4.0,
  },
  "1092": {
    id: "1092",
    naam: "Orlando Mosquera",
    club: "Panama",
    positie: "GK",
    prijs: 4.0,
  },
  "1093": {
    id: "1093",
    naam: "Andrés Andrade",
    club: "Panama",
    positie: "DEF",
    prijs: 4.0,
  },
  "1094": {
    id: "1094",
    naam: "Fidel Escobar",
    club: "Panama",
    positie: "DEF",
    prijs: 4.0,
  },
  "1095": {
    id: "1095",
    naam: "Jorge Gutiérrez",
    club: "Panama",
    positie: "DEF",
    prijs: 4.0,
  },
  "1096": {
    id: "1096",
    naam: "José Córdoba",
    club: "Panama",
    positie: "DEF",
    prijs: 4.0,
  },
  "1097": {
    id: "1097",
    naam: "Adalberto Carrasquilla",
    club: "Panama",
    positie: "MID",
    prijs: 4.0,
  },
  "1098": {
    id: "1098",
    naam: "Aníbal Godoy",
    club: "Panama",
    positie: "MID",
    prijs: 4.0,
  },
  "1099": {
    id: "1099",
    naam: "César Blackman",
    club: "Panama",
    positie: "DEF",
    prijs: 4.0,
  },
  "1100": {
    id: "1100",
    naam: "José Luis Rodríguez",
    club: "Panama",
    positie: "MID",
    prijs: 4.0,
  },
  "1101": {
    id: "1101",
    naam: "Cecilio Waterman",
    club: "Panama",
    positie: "FWD",
    prijs: 4.0,
  },
  "1102": {
    id: "1102",
    naam: "Ismael Díaz",
    club: "Panama",
    positie: "FWD",
    prijs: 4.0,
  },
  "1103": {
    id: "1103",
    naam: "José Fajardo",
    club: "Panama",
    positie: "FWD",
    prijs: 4.0,
  },
  "1104": {
    id: "1104",
    naam: "Yoel Bárcenas",
    club: "Panama",
    positie: "FWD",
    prijs: 4.0,
  },
  "1105": {
    id: "1105",
    naam: "Mahmud Abunada",
    club: "Qatar",
    positie: "GK",
    prijs: 4.0,
  },
  "1106": {
    id: "1106",
    naam: "Meshaal Barsham",
    club: "Qatar",
    positie: "GK",
    prijs: 4.0,
  },
  "1107": {
    id: "1107",
    naam: "Boualem Khoukhi",
    club: "Qatar",
    positie: "DEF",
    prijs: 4.0,
  },
  "1108": {
    id: "1108",
    naam: "Homam Ahmed",
    club: "Qatar",
    positie: "DEF",
    prijs: 4.0,
  },
  "1109": {
    id: "1109",
    naam: "Pedro Miguel",
    club: "Qatar",
    positie: "DEF",
    prijs: 4.0,
  },
  "1111": {
    id: "1111",
    naam: "Karim Boudiaf",
    club: "Qatar",
    positie: "MID",
    prijs: 4.0,
  },
  "1112": {
    id: "1112",
    naam: "Hassan Al-Haydos",
    club: "Qatar",
    positie: "MID",
    prijs: 4.0,
  },
  "1113": {
    id: "1113",
    naam: "Mohammed Al-Owais",
    club: "Saudi-Arabië",
    positie: "GK",
    prijs: 4.0,
  },
  "1114": {
    id: "1114",
    naam: "Nawaf Al-Aqidi",
    club: "Saudi-Arabië",
    positie: "GK",
    prijs: 4.0,
  },
  "1115": {
    id: "1115",
    naam: "Abdulelah Al-Amri",
    club: "Saudi-Arabië",
    positie: "DEF",
    prijs: 4.0,
  },
  "1116": {
    id: "1116",
    naam: "Ali Lajami",
    club: "Saudi-Arabië",
    positie: "DEF",
    prijs: 4.0,
  },
  "1117": {
    id: "1117",
    naam: "Nawaf Boushal",
    club: "Saudi-Arabië",
    positie: "DEF",
    prijs: 4.0,
  },
  "1118": {
    id: "1118",
    naam: "Mohamed Kanno",
    club: "Saudi-Arabië",
    positie: "MID",
    prijs: 4.0,
  },
  "1119": {
    id: "1119",
    naam: "Abdullah Al-Hamdan",
    club: "Saudi-Arabië",
    positie: "FWD",
    prijs: 4.0,
  },
  "1131": {
    id: "1131",
    naam: "Sabri Ben Hessen",
    club: "Tunesië",
    positie: "GK",
    prijs: 4.0,
  },
  "1143": {
    id: "1143",
    naam: "Trevor Doornbusch",
    club: "Curaçao",
    positie: "GK",
    prijs: 3.5,
  },
  "1144": {
    id: "1144",
    naam: "Tyrick Bodak",
    club: "Curaçao",
    positie: "GK",
    prijs: 3.5,
  },
  "1145": {
    id: "1145",
    naam: "Deveron Fonville",
    club: "Curaçao",
    positie: "DEF",
    prijs: 3.5,
  },
  "1146": {
    id: "1146",
    naam: "Ar\'jany Martha",
    club: "Curaçao",
    positie: "MID",
    prijs: 3.5,
  },
  "1147": {
    id: "1147",
    naam: "Godfried Roemeratoe",
    club: "Curaçao",
    positie: "MID",
    prijs: 3.5,
  },
  "1148": {
    id: "1148",
    naam: "Kevin Felida",
    club: "Curaçao",
    positie: "MID",
    prijs: 3.5,
  },
  "1149": {
    id: "1149",
    naam: "Tyrese Noslin",
    club: "Curaçao",
    positie: "MID",
    prijs: 3.5,
  },
  "1150": {
    id: "1150",
    naam: "Jearl Margaritha",
    club: "Curaçao",
    positie: "FWD",
    prijs: 3.5,
  },
  "1151": {
    id: "1151",
    naam: "Jeremy Antonisse",
    club: "Curaçao",
    positie: "FWD",
    prijs: 3.5,
  },
  "1152": {
    id: "1152",
    naam: "Johny Placide",
    club: "Haïti",
    positie: "GK",
    prijs: 3.5,
  },
  "1153": {
    id: "1153",
    naam: "Carlens Arcus",
    club: "Haïti",
    positie: "DEF",
    prijs: 3.5,
  },
  "1154": {
    id: "1154",
    naam: "Martin Expérience",
    club: "Haïti",
    positie: "DEF",
    prijs: 3.5,
  },
  "1155": {
    id: "1155",
    naam: "Fahad Talib",
    club: "Irak",
    positie: "GK",
    prijs: 3.5,
  },
  "1156": {
    id: "1156",
    naam: "Ahmed Maknzi",
    club: "Irak",
    positie: "DEF",
    prijs: 3.5,
  },
  "1157": {
    id: "1157",
    naam: "Rebin Sulaka",
    club: "Irak",
    positie: "DEF",
    prijs: 3.5,
  },
  "1158": {
    id: "1158",
    naam: "Kevin Yakob",
    club: "Irak",
    positie: "MID",
    prijs: 3.5,
  },
  "1159": {
    id: "1159",
    naam: "Marko Farji",
    club: "Irak",
    positie: "MID",
    prijs: 3.5,
  },
  "1160": {
    id: "1160",
    naam: "Youssef Amyn",
    club: "Irak",
    positie: "MID",
    prijs: 3.5,
  },
  "1161": {
    id: "1161",
    naam: "Zaid Ismael",
    club: "Irak",
    positie: "MID",
    prijs: 3.5,
  },
  "1162": {
    id: "1162",
    naam: "Ali Yousif",
    club: "Irak",
    positie: "FWD",
    prijs: 3.5,
  },
  "1164": {
    id: "1164",
    naam: "Yazeed Abulaila",
    club: "Jordanië",
    positie: "GK",
    prijs: 3.5,
  },
  "1166": {
    id: "1166",
    naam: "Mohammad Abu Hashish",
    club: "Jordanië",
    positie: "DEF",
    prijs: 3.5,
  },
  "1167": {
    id: "1167",
    naam: "Mohannad Abu Taha",
    club: "Jordanië",
    positie: "DEF",
    prijs: 3.5,
  },
  "1168": {
    id: "1168",
    naam: "Yazan Al-Arab",
    club: "Jordanië",
    positie: "DEF",
    prijs: 3.5,
  },
  "1169": {
    id: "1169",
    naam: "Ibrahim Saadeh",
    club: "Jordanië",
    positie: "MID",
    prijs: 3.5,
  },
  "1170": {
    id: "1170",
    naam: "Nizar Al-Rashdan",
    club: "Jordanië",
    positie: "MID",
    prijs: 3.5,
  },
  "1171": {
    id: "1171",
    naam: "Noor Al-Rawabdeh",
    club: "Jordanië",
    positie: "MID",
    prijs: 3.5,
  },
  "1172": {
    id: "1172",
    naam: "Rajaee Ayed",
    club: "Jordanië",
    positie: "MID",
    prijs: 3.5,
  },
  "1174": {
    id: "1174",
    naam: "Mahmoud Al-Mardi",
    club: "Jordanië",
    positie: "FWD",
    prijs: 3.5,
  },
  "1175": {
    id: "1175",
    naam: "Mohammad Abu Zrayq",
    club: "Jordanië",
    positie: "FWD",
    prijs: 3.5,
  },
  "1176": {
    id: "1176",
    naam: "César Samudio",
    club: "Panama",
    positie: "GK",
    prijs: 3.5,
  },
  "1177": {
    id: "1177",
    naam: "Edgardo Fariña",
    club: "Panama",
    positie: "DEF",
    prijs: 3.5,
  },
  "1178": {
    id: "1178",
    naam: "Jiovany Ramos",
    club: "Panama",
    positie: "DEF",
    prijs: 3.5,
  },
  "1179": {
    id: "1179",
    naam: "Carlos Harvey",
    club: "Panama",
    positie: "MID",
    prijs: 3.5,
  },
  "1180": {
    id: "1180",
    naam: "Cristian Martínez",
    club: "Panama",
    positie: "MID",
    prijs: 3.5,
  },
  "1181": {
    id: "1181",
    naam: "Eric Davis",
    club: "Panama",
    positie: "MID",
    prijs: 3.5,
  },
  "1182": {
    id: "1182",
    naam: "Azarías Londoño",
    club: "Panama",
    positie: "FWD",
    prijs: 3.5,
  },
  "1183": {
    id: "1183",
    naam: "César Yanis",
    club: "Panama",
    positie: "FWD",
    prijs: 3.5,
  },
  "1184": {
    id: "1184",
    naam: "Salah Zakaria",
    club: "Qatar",
    positie: "GK",
    prijs: 3.5,
  },
  "1185": {
    id: "1185",
    naam: "Ayoub Al-Oui",
    club: "Qatar",
    positie: "DEF",
    prijs: 3.5,
  },
  "1187": {
    id: "1187",
    naam: "Lucas Mendes",
    club: "Qatar",
    positie: "DEF",
    prijs: 3.5,
  },
  "1188": {
    id: "1188",
    naam: "Sultan Al-Braik",
    club: "Qatar",
    positie: "DEF",
    prijs: 3.5,
  },
  "1189": {
    id: "1189",
    naam: "Ahmed Fatahy",
    club: "Qatar",
    positie: "MID",
    prijs: 3.5,
  },
  "1190": {
    id: "1190",
    naam: "Assim Madibo",
    club: "Qatar",
    positie: "MID",
    prijs: 3.5,
  },
  "1193": {
    id: "1193",
    naam: "Ahmed Al-Ganehi",
    club: "Qatar",
    positie: "FWD",
    prijs: 3.5,
  },
  "1194": {
    id: "1194",
    naam: "Edmilson Junior",
    club: "Qatar",
    positie: "FWD",
    prijs: 3.5,
  },
  "1195": {
    id: "1195",
    naam: "Yusuf Abdurisag",
    club: "Qatar",
    positie: "FWD",
    prijs: 3.5,
  },
  "1196": {
    id: "1196",
    naam: "Ahmed Al-Kassar",
    club: "Saudi-Arabië",
    positie: "GK",
    prijs: 3.5,
  },
  "1197": {
    id: "1197",
    naam: "Ali Majrashi",
    club: "Saudi-Arabië",
    positie: "DEF",
    prijs: 3.5,
  },
  "1198": {
    id: "1198",
    naam: "Hasan Kadesh",
    club: "Saudi-Arabië",
    positie: "DEF",
    prijs: 3.5,
  },
  "1200": {
    id: "1200",
    naam: "Abdullah Al-Khaibari",
    club: "Saudi-Arabië",
    positie: "MID",
    prijs: 3.5,
  },
  "1201": {
    id: "1201",
    naam: "Ziyad Al-Johani",
    club: "Saudi-Arabië",
    positie: "MID",
    prijs: 3.5,
  },
  "1202": {
    id: "1202",
    naam: "Ayman Yahya",
    club: "Saudi-Arabië",
    positie: "FWD",
    prijs: 3.5,
  },
  "1228": {
    id: "1228",
    naam: "Alexandre Pierre",
    club: "Haïti",
    positie: "GK",
    prijs: 3.0,
  },
  "1229": {
    id: "1229",
    naam: "Josué Duverger",
    club: "Haïti",
    positie: "GK",
    prijs: 3.0,
  },
  "1231": {
    id: "1231",
    naam: "Duke Lacroix",
    club: "Haïti",
    positie: "DEF",
    prijs: 3.0,
  },
  "1235": {
    id: "1235",
    naam: "Abdallah Al-Fakhouri",
    club: "Jordanië",
    positie: "GK",
    prijs: 3.0,
  },
  "1236": {
    id: "1236",
    naam: "Nour Bani Attiah",
    club: "Jordanië",
    positie: "GK",
    prijs: 3.0,
  },
  "1238": {
    id: "1238",
    naam: "Husam Abu Dahab",
    club: "Jordanië",
    positie: "DEF",
    prijs: 3.0,
  },
  "1240": {
    id: "1240",
    naam: "Mohammad Abualnadi",
    club: "Jordanië",
    positie: "DEF",
    prijs: 3.0,
  },
  "1241": {
    id: "1241",
    naam: "Saed Al-Rosan",
    club: "Jordanië",
    positie: "DEF",
    prijs: 3.0,
  },
  "1242": {
    id: "1242",
    naam: "Amer Jamous",
    club: "Jordanië",
    positie: "MID",
    prijs: 3.0,
  },
  "1244": {
    id: "1244",
    naam: "Odeh Al-Fakhouri",
    club: "Jordanië",
    positie: "FWD",
    prijs: 3.0,
  },
  "1246": {
    id: "1246",
    naam: "Roderick Miller",
    club: "Panama",
    positie: "DEF",
    prijs: 3.0,
  },
  "1248": {
    id: "1248",
    naam: "Al-Hashmi Al-Hussain",
    club: "Qatar",
    positie: "DEF",
    prijs: 3.0,
  },
  "1250": {
    id: "1250",
    naam: "Mohamed Manai",
    club: "Qatar",
    positie: "MID",
    prijs: 3.0,
  },
  "1252": {
    id: "1252",
    naam: "Saleh Al-Shehri",
    club: "Saudi-Arabië",
    positie: "FWD",
    prijs: 3.0,
  },
  "1253": {
    id: "1253",
    naam: "Sultan Mandash",
    club: "Saudi-Arabië",
    positie: "FWD",
    prijs: 3.0,
  },
  "1261": {
    id: "1261",
    naam: "Abdelmouhib Chamakh",
    club: "Tunesië",
    positie: "GK",
    prijs: 4.0,
  },
  "1262": {
    id: "1262",
    naam: "Mortadha Ben Ouanes",
    club: "Tunesië",
    positie: "DEF",
    prijs: 4.5,
  },
  "1263": {
    id: "1263",
    naam: "Anis Ben Slimane",
    club: "Tunesië",
    positie: "MID",
    prijs: 5.0,
  },
  "1264": {
    id: "1264",
    naam: "Rani Khedira",
    club: "Tunesië",
    positie: "MID",
    prijs: 5.0,
  },
  "1265": {
    id: "1265",
    naam: "Hadj Mahmoud",
    club: "Tunesië",
    positie: "MID",
    prijs: 4.0,
  },
  "1308": {
    id: "1308",
    naam: "Jindrich Stanek",
    club: "Tsjechië",
    positie: "GK",
    prijs: 6.5,
  },
  "1309": {
    id: "1309",
    naam: "David Doudera",
    club: "Tsjechië",
    positie: "DEF",
    prijs: 6.5,
  },
  "1310": {
    id: "1310",
    naam: "David Zima",
    club: "Tsjechië",
    positie: "DEF",
    prijs: 6.5,
  },
  "1311": {
    id: "1311",
    naam: "Hugo Sochurek",
    club: "Tsjechië",
    positie: "MID",
    prijs: 5.5,
  },
  "1312": {
    id: "1312",
    naam: "Alexandr Sojka",
    club: "Tsjechië",
    positie: "MID",
    prijs: 5.5,
  },
  "1314": {
    id: "1314",
    naam: "Jan Kuchta",
    club: "Tsjechië",
    positie: "FWD",
    prijs: 6.5,
  },
  "1338": {
    id: "1338",
    naam: "Alberto Quintero",
    club: "Panama",
    positie: "MID",
    prijs: 3.0,
  },
  "1339": {
    id: "1339",
    naam: "Tomás Rodríguez",
    club: "Panama",
    positie: "FWD",
    prijs: 3.0,
  },
  "1420": {
    id: "1420",
    naam: "Juan Sanabria",
    club: "Uruguay",
    positie: "MID",
    prijs: 7.0,
  },
  "1421": {
    id: "1421",
    naam: "Rodrigo Zalazar",
    club: "Uruguay",
    positie: "MID",
    prijs: 8.0,
  },
  "1422": {
    id: "1422",
    naam: "Rodrigo Aguirre",
    club: "Uruguay",
    positie: "FWD",
    prijs: 7.0,
  },
  "1424": {
    id: "1424",
    naam: "Moteb Al-Harbi",
    club: "Saudi-Arabië",
    positie: "DEF",
    prijs: 3.5,
  },
  "1425": {
    id: "1425",
    naam: "Mohammed Abu Al-Shamat",
    club: "Saudi-Arabië",
    positie: "DEF",
    prijs: 3.5,
  },
  "1426": {
    id: "1426",
    naam: "Hassan Al-Tambakti",
    club: "Saudi-Arabië",
    positie: "DEF",
    prijs: 3.5,
  },
  "1427": {
    id: "1427",
    naam: "Jehad Thakri",
    club: "Saudi-Arabië",
    positie: "DEF",
    prijs: 3.5,
  },
  "1428": {
    id: "1428",
    naam: "Nasser Al-Dawsari",
    club: "Saudi-Arabië",
    positie: "MID",
    prijs: 3.5,
  },
  "1429": {
    id: "1429",
    naam: "Alaa Hejji",
    club: "Saudi-Arabië",
    positie: "MID",
    prijs: 3.5,
  },
  "1430": {
    id: "1430",
    naam: "Khalid Al Ghannam",
    club: "Saudi-Arabië",
    positie: "FWD",
    prijs: 3.0,
  },
  "1435": {
    id: "1435",
    naam: "Mustafa Saadoon",
    club: "Irak",
    positie: "DEF",
    prijs: 3.5,
  },
  "1436": {
    id: "1436",
    naam: "Ahmed Qasem",
    club: "Irak",
    positie: "FWD",
    prijs: 4.0,
  },
  "1446": {
    id: "1446",
    naam: "Issa Laye",
    club: "Qatar",
    positie: "DEF",
    prijs: 3.0,
  },
  "1447": {
    id: "1447",
    naam: "Jassem Gaber",
    club: "Qatar",
    positie: "DEF",
    prijs: 3.5,
  },
  "1448": {
    id: "1448",
    naam: "Abdulaziz Hatem",
    club: "Qatar",
    positie: "MID",
    prijs: 3.5,
  },
  "1449": {
    id: "1449",
    naam: "Ahmed Alaaeldin",
    club: "Qatar",
    positie: "FWD",
    prijs: 3.5,
  },
  "1450": {
    id: "1450",
    naam: "Tahsin Mohammed Jamshid",
    club: "Qatar",
    positie: "FWD",
    prijs: 3.0,
  },
  "1451": {
    id: "1451",
    naam: "Mohammed Muntari",
    club: "Qatar",
    positie: "FWD",
    prijs: 3.5,
  },
  "1452": {
    id: "1452",
    naam: "Çaglar Söyüncü",
    club: "Turkije",
    positie: "DEF",
    prijs: 8.0,
  },
  "1453": {
    id: "1453",
    naam: "Can Uzun",
    club: "Turkije",
    positie: "FWD",
    prijs: 8.0,
  },
  "1462": {
    id: "1462",
    naam: "Abdallah Nasib",
    club: "Jordanië",
    positie: "DEF",
    prijs: 3.0,
  },
  "1463": {
    id: "1463",
    naam: "Saleem Obaid",
    club: "Jordanië",
    positie: "DEF",
    prijs: 3.0,
  },
  "1464": {
    id: "1464",
    naam: "Anas Badawi",
    club: "Jordanië",
    positie: "DEF",
    prijs: 3.0,
  },
  "1465": {
    id: "1465",
    naam: "Mohammad Al-Dawoud",
    club: "Jordanië",
    positie: "MID",
    prijs: 3.0,
  },
  "1466": {
    id: "1466",
    naam: "Aly Azaiza",
    club: "Jordanië",
    positie: "FWD",
    prijs: 3.0,
  },
  "1568": {
    id: "1568",
    naam: "Mohammad Abu Ghoush",
    club: "Jordanië",
    positie: "DEF",
    prijs: 3.0,
  }
};

export function getInactivePlayer(id: string): PlayerRecord | undefined {
  return INACTIVE_WK_PLAYERS[id];
}
